version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prince
      MYSQL_DATABASE: students

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: prince

